### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by joelrivas** [larusba/neo4j-couchbase-connector#1]
Hi everyone, 

I'm looking to use this connector, but I can't find any proper documentation on how to integrate it with my project, or how to even try the tests. Steps to follow will be appreciated.

**Comment by omarlarus** [comment]
Hi @joelrivas ,
there's a new project to connect couchbase (or any JSON source) to Neo4j. Take a look at [doc2graph](https://github.com/larusba/doc2graph)

**Comment by joelrivas** [comment]
Thanks a lot!!
